services:
  postgres_moteros:
    image: postgis/postgis:15-3.3
    container_name: moteros_db
    restart: always
    environment:
      POSTGRES_USER: admin_motero
      POSTGRES_PASSWORD: TuPasswordSegura2026_!
      POSTGRES_DB: moteros_colombia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
