-- BLOQUE 3: reportes privados, bloqueo bilateral y moderacion.
BEGIN;

CREATE TABLE IF NOT EXISTS public.motoposada_user_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocker_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  blocked_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  request_id BIGINT REFERENCES public.motoposada_requests(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT motoposada_user_blocks_not_self CHECK (blocker_id <> blocked_id),
  CONSTRAINT motoposada_user_blocks_unique UNIQUE (blocker_id, blocked_id)
);

CREATE INDEX IF NOT EXISTS idx_motoposada_blocks_blocked
  ON public.motoposada_user_blocks(blocked_id, blocker_id);

ALTER TABLE public.motoposada_user_blocks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.motoposada_user_blocks FROM anon, authenticated;
GRANT SELECT ON public.motoposada_user_blocks TO authenticated;

DROP POLICY IF EXISTS "motoposada_blocks_select_own" ON public.motoposada_user_blocks;
CREATE POLICY "motoposada_blocks_select_own"
ON public.motoposada_user_blocks FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = blocker_id);

CREATE TABLE IF NOT EXISTS public.motoposada_incident_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES public.motoposada_requests(id) ON DELETE RESTRICT,
  reporter_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  reported_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  category TEXT NOT NULL CHECK (category IN ('behavior','harassment','property_damage','fraud','other')),
  description TEXT NOT NULL CHECK (char_length(description) BETWEEN 10 AND 1000),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','reviewing','resolved','dismissed')),
  moderator_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  moderator_note TEXT CHECK (moderator_note IS NULL OR char_length(moderator_note) <= 1000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ,
  CONSTRAINT motoposada_incident_not_self CHECK (reporter_id <> reported_id),
  CONSTRAINT motoposada_incident_unique UNIQUE (request_id, reporter_id, category)
);

CREATE INDEX IF NOT EXISTS idx_motoposada_incidents_moderation
  ON public.motoposada_incident_reports(status, created_at);
CREATE INDEX IF NOT EXISTS idx_motoposada_incidents_reported
  ON public.motoposada_incident_reports(reported_id, created_at DESC);

ALTER TABLE public.motoposada_incident_reports ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.motoposada_incident_reports FROM anon, authenticated;
GRANT SELECT ON public.motoposada_incident_reports TO authenticated;

DROP POLICY IF EXISTS "motoposada_incidents_select_reporter_or_admin" ON public.motoposada_incident_reports;
CREATE POLICY "motoposada_incidents_select_reporter_or_admin"
ON public.motoposada_incident_reports FOR SELECT TO authenticated
USING (
  (SELECT auth.uid()) = reporter_id
  OR (SELECT public.is_admin())
);

CREATE OR REPLACE FUNCTION public.report_motoposada_incident(
  p_request_id BIGINT,
  p_category TEXT,
  p_description TEXT
) RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_req RECORD;
  v_reported UUID;
  v_id BIGINT;
  v_description TEXT := BTRIM(p_description);
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  IF p_category NOT IN ('behavior','harassment','property_damage','fraud','other') THEN
    RAISE EXCEPTION 'invalid_report_category';
  END IF;
  IF char_length(v_description) NOT BETWEEN 10 AND 1000 THEN
    RAISE EXCEPTION 'invalid_report_description';
  END IF;

  SELECT r.guest_id, r.status, m.user_id AS host_id
    INTO v_req
    FROM public.motoposada_requests r
    JOIN public.motoposadas m ON m.id = r.motoposada_id
   WHERE r.id = p_request_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'request_not_found'; END IF;
  IF v_req.status NOT IN ('approved','completed') THEN RAISE EXCEPTION 'stay_not_eligible_for_report'; END IF;

  IF v_uid = v_req.guest_id THEN v_reported := v_req.host_id;
  ELSIF v_uid = v_req.host_id THEN v_reported := v_req.guest_id;
  ELSE RAISE EXCEPTION 'not_participant';
  END IF;

  INSERT INTO public.motoposada_incident_reports(
    request_id, reporter_id, reported_id, category, description
  ) VALUES (p_request_id, v_uid, v_reported, p_category, v_description)
  RETURNING id INTO v_id;
  RETURN v_id;
EXCEPTION
  WHEN unique_violation THEN RAISE EXCEPTION 'incident_already_reported';
END;
$$;

CREATE OR REPLACE FUNCTION public.block_motoposada_participant(p_request_id BIGINT)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_req RECORD;
  v_blocked UUID;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  SELECT r.guest_id, m.user_id AS host_id
    INTO v_req
    FROM public.motoposada_requests r
    JOIN public.motoposadas m ON m.id = r.motoposada_id
   WHERE r.id = p_request_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'request_not_found'; END IF;

  IF v_uid = v_req.guest_id THEN v_blocked := v_req.host_id;
  ELSIF v_uid = v_req.host_id THEN v_blocked := v_req.guest_id;
  ELSE RAISE EXCEPTION 'not_participant';
  END IF;
  IF v_blocked = v_uid THEN RAISE EXCEPTION 'cannot_block_self'; END IF;

  INSERT INTO public.motoposada_user_blocks(blocker_id, blocked_id, request_id)
  VALUES (v_uid, v_blocked, p_request_id)
  ON CONFLICT (blocker_id, blocked_id) DO NOTHING;
END;
$$;

CREATE OR REPLACE FUNCTION public.unblock_motoposada_user(p_blocked_id UUID)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE v_uid UUID := auth.uid();
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  DELETE FROM public.motoposada_user_blocks
   WHERE blocker_id = v_uid AND blocked_id = p_blocked_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.moderate_motoposada_incident(
  p_report_id BIGINT,
  p_status TEXT,
  p_note TEXT DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE v_uid UUID := auth.uid();
BEGIN
  IF v_uid IS NULL OR NOT public.is_admin() THEN RAISE EXCEPTION 'admin_required'; END IF;
  IF p_status NOT IN ('reviewing','resolved','dismissed') THEN RAISE EXCEPTION 'invalid_report_status'; END IF;
  IF char_length(COALESCE(p_note, '')) > 1000 THEN RAISE EXCEPTION 'moderator_note_too_long'; END IF;
  UPDATE public.motoposada_incident_reports
     SET status = p_status,
         moderator_id = v_uid,
         moderator_note = NULLIF(BTRIM(p_note), ''),
         reviewed_at = CASE WHEN p_status IN ('resolved','dismissed') THEN now() ELSE NULL END
   WHERE id = p_report_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'report_not_found'; END IF;
END;
$$;

-- Backstop central: protege INSERT y el paso a approved aunque otro cliente
-- antiguo intente usar una ruta diferente a request_motoposada.
CREATE OR REPLACE FUNCTION public.enforce_motoposada_user_block()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE v_host_id UUID;
BEGIN
  IF NEW.status NOT IN ('pending','approved') THEN RETURN NEW; END IF;
  SELECT user_id INTO v_host_id FROM public.motoposadas WHERE id = NEW.motoposada_id;
  IF EXISTS (
    SELECT 1 FROM public.motoposada_user_blocks b
     WHERE (b.blocker_id = NEW.guest_id AND b.blocked_id = v_host_id)
        OR (b.blocker_id = v_host_id AND b.blocked_id = NEW.guest_id)
  ) THEN RAISE EXCEPTION 'motoposada_user_blocked';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_motoposada_user_block ON public.motoposada_requests;
CREATE TRIGGER trg_enforce_motoposada_user_block
BEFORE INSERT OR UPDATE OF status ON public.motoposada_requests
FOR EACH ROW EXECUTE FUNCTION public.enforce_motoposada_user_block();

REVOKE ALL ON FUNCTION public.report_motoposada_incident(BIGINT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.block_motoposada_participant(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.unblock_motoposada_user(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.moderate_motoposada_incident(BIGINT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.enforce_motoposada_user_block() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.report_motoposada_incident(BIGINT,TEXT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.block_motoposada_participant(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unblock_motoposada_user(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.moderate_motoposada_incident(BIGINT,TEXT,TEXT) TO authenticated;

COMMIT;
