-- BLOQUE 4: cola administrativa, decisiones auditables, suspensiones y apelaciones.
BEGIN;

CREATE TABLE public.motoposada_moderation_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES public.motoposada_incident_reports(id) ON DELETE RESTRICT,
  moderator_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  action TEXT NOT NULL CHECK (action IN ('start_review','dismiss','warn','suspend','ban','lift_suspension')),
  note TEXT NOT NULL CHECK (char_length(btrim(note)) BETWEEN 10 AND 1000),
  suspension_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((action = 'suspend' AND suspension_until > created_at) OR (action <> 'suspend' AND suspension_until IS NULL))
);

CREATE TABLE public.motoposada_user_suspensions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  report_id BIGINT NOT NULL REFERENCES public.motoposada_incident_reports(id) ON DELETE RESTRICT,
  action_id BIGINT NOT NULL UNIQUE REFERENCES public.motoposada_moderation_actions(id) ON DELETE RESTRICT,
  kind TEXT NOT NULL CHECK (kind IN ('temporary','permanent')),
  starts_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ends_at TIMESTAMPTZ,
  lifted_at TIMESTAMPTZ,
  lifted_by UUID REFERENCES public.users(id) ON DELETE RESTRICT,
  CHECK ((kind = 'temporary' AND ends_at > starts_at) OR (kind = 'permanent' AND ends_at IS NULL))
);

CREATE UNIQUE INDEX motoposada_one_active_suspension_per_user
  ON public.motoposada_user_suspensions(user_id)
  WHERE lifted_at IS NULL;
CREATE INDEX motoposada_moderation_actions_report_idx ON public.motoposada_moderation_actions(report_id, created_at);

CREATE TABLE public.motoposada_moderation_appeals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suspension_id BIGINT NOT NULL UNIQUE REFERENCES public.motoposada_user_suspensions(id) ON DELETE RESTRICT,
  appellant_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  reason TEXT NOT NULL CHECK (char_length(btrim(reason)) BETWEEN 20 AND 1500),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
  reviewer_id UUID REFERENCES public.users(id) ON DELETE RESTRICT,
  reviewer_note TEXT CHECK (reviewer_note IS NULL OR char_length(btrim(reviewer_note)) BETWEEN 10 AND 1000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ
);

ALTER TABLE public.motoposada_moderation_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.motoposada_user_suspensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.motoposada_moderation_appeals ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.motoposada_moderation_actions, public.motoposada_user_suspensions, public.motoposada_moderation_appeals FROM anon, authenticated;
GRANT SELECT ON public.motoposada_user_suspensions, public.motoposada_moderation_appeals TO authenticated;

CREATE POLICY motoposada_suspensions_select_own_or_admin ON public.motoposada_user_suspensions
FOR SELECT TO authenticated USING ((SELECT auth.uid()) = user_id OR (SELECT public.is_admin()));
CREATE POLICY motoposada_appeals_select_own_or_admin ON public.motoposada_moderation_appeals
FOR SELECT TO authenticated USING ((SELECT auth.uid()) = appellant_id OR (SELECT public.is_admin()));

CREATE OR REPLACE FUNCTION public.get_motoposada_moderation_queue(p_status TEXT DEFAULT NULL)
RETURNS TABLE(report_id BIGINT, category TEXT, description TEXT, status TEXT, created_at TIMESTAMPTZ, reporter_id UUID, reported_id UUID, request_id BIGINT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.is_admin() THEN RAISE EXCEPTION 'admin_required'; END IF;
  IF p_status IS NOT NULL AND p_status NOT IN ('open','reviewing','resolved','dismissed') THEN RAISE EXCEPTION 'invalid_report_status'; END IF;
  RETURN QUERY SELECT r.id,r.category,r.description,r.status,r.created_at,r.reporter_id,r.reported_id,r.request_id
  FROM public.motoposada_incident_reports r
  WHERE p_status IS NULL OR r.status = p_status ORDER BY r.created_at ASC;
END $$;

CREATE OR REPLACE FUNCTION public.decide_motoposada_incident(p_report_id BIGINT, p_action TEXT, p_note TEXT, p_suspension_until TIMESTAMPTZ DEFAULT NULL)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_uid UUID := auth.uid(); v_report RECORD; v_action_id BIGINT;
BEGIN
  IF v_uid IS NULL OR NOT public.is_admin() THEN RAISE EXCEPTION 'admin_required'; END IF;
  IF p_action NOT IN ('start_review','dismiss','warn','suspend','ban') THEN RAISE EXCEPTION 'invalid_moderation_action'; END IF;
  IF char_length(btrim(coalesce(p_note,''))) NOT BETWEEN 10 AND 1000 THEN RAISE EXCEPTION 'invalid_moderator_note'; END IF;
  IF (p_action='suspend' AND (p_suspension_until IS NULL OR p_suspension_until <= now())) OR (p_action<>'suspend' AND p_suspension_until IS NOT NULL) THEN RAISE EXCEPTION 'invalid_suspension_until'; END IF;
  SELECT * INTO v_report FROM public.motoposada_incident_reports WHERE id=p_report_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'report_not_found'; END IF;
  IF v_report.status IN ('resolved','dismissed') THEN RAISE EXCEPTION 'report_already_closed'; END IF;
  INSERT INTO public.motoposada_moderation_actions(report_id,moderator_id,action,note,suspension_until)
  VALUES(p_report_id,v_uid,p_action,btrim(p_note),p_suspension_until) RETURNING id INTO v_action_id;
  IF p_action IN ('suspend','ban') THEN
    UPDATE public.motoposada_user_suspensions SET lifted_at=now(),lifted_by=v_uid
    WHERE user_id=v_report.reported_id AND kind='temporary' AND ends_at<=now() AND lifted_at IS NULL;
    IF EXISTS(SELECT 1 FROM public.motoposada_user_suspensions s WHERE s.user_id=v_report.reported_id AND s.lifted_at IS NULL) THEN RAISE EXCEPTION 'active_suspension_exists'; END IF;
    INSERT INTO public.motoposada_user_suspensions(user_id,report_id,action_id,kind,ends_at)
    VALUES(v_report.reported_id,p_report_id,v_action_id,CASE WHEN p_action='ban' THEN 'permanent' ELSE 'temporary' END,p_suspension_until);
  END IF;
  UPDATE public.motoposada_incident_reports SET status=CASE WHEN p_action='start_review' THEN 'reviewing' WHEN p_action='dismiss' THEN 'dismissed' ELSE 'resolved' END,
    moderator_id=v_uid, moderator_note=btrim(p_note), reviewed_at=CASE WHEN p_action='start_review' THEN NULL ELSE now() END WHERE id=p_report_id;
  RETURN v_action_id;
END $$;

CREATE OR REPLACE FUNCTION public.appeal_motoposada_suspension(p_suspension_id BIGINT,p_reason TEXT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_uid UUID:=auth.uid(); v_id BIGINT;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  IF char_length(btrim(coalesce(p_reason,''))) NOT BETWEEN 20 AND 1500 THEN RAISE EXCEPTION 'invalid_appeal_reason'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.motoposada_user_suspensions WHERE id=p_suspension_id AND user_id=v_uid AND lifted_at IS NULL AND (kind='permanent' OR ends_at>now())) THEN RAISE EXCEPTION 'suspension_not_found'; END IF;
  INSERT INTO public.motoposada_moderation_appeals(suspension_id,appellant_id,reason) VALUES(p_suspension_id,v_uid,btrim(p_reason)) RETURNING id INTO v_id;
  RETURN v_id;
EXCEPTION WHEN unique_violation THEN RAISE EXCEPTION 'appeal_already_exists';
END $$;

CREATE OR REPLACE FUNCTION public.review_motoposada_appeal(p_appeal_id BIGINT,p_accept BOOLEAN,p_note TEXT)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_uid UUID:=auth.uid(); v_appeal RECORD; v_report_id BIGINT; v_action_id BIGINT;
BEGIN
  IF v_uid IS NULL OR NOT public.is_admin() THEN RAISE EXCEPTION 'admin_required'; END IF;
  IF char_length(btrim(coalesce(p_note,''))) NOT BETWEEN 10 AND 1000 THEN RAISE EXCEPTION 'invalid_reviewer_note'; END IF;
  SELECT * INTO v_appeal FROM public.motoposada_moderation_appeals WHERE id=p_appeal_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'appeal_not_found'; END IF;
  IF v_appeal.status <> 'pending' THEN RAISE EXCEPTION 'appeal_already_reviewed'; END IF;
  SELECT report_id INTO v_report_id FROM public.motoposada_user_suspensions WHERE id=v_appeal.suspension_id;
  UPDATE public.motoposada_moderation_appeals SET status=CASE WHEN p_accept THEN 'accepted' ELSE 'rejected' END,reviewer_id=v_uid,reviewer_note=btrim(p_note),reviewed_at=now() WHERE id=p_appeal_id;
  IF p_accept THEN
    INSERT INTO public.motoposada_moderation_actions(report_id,moderator_id,action,note) VALUES(v_report_id,v_uid,'lift_suspension',btrim(p_note)) RETURNING id INTO v_action_id;
    UPDATE public.motoposada_user_suspensions SET lifted_at=now(),lifted_by=v_uid WHERE id=v_appeal.suspension_id AND lifted_at IS NULL;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.is_motoposada_suspended(p_user_id UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
  SELECT EXISTS(SELECT 1 FROM public.motoposada_user_suspensions s WHERE s.user_id=p_user_id AND s.lifted_at IS NULL AND (s.kind='permanent' OR s.ends_at>now()))
$$;

-- Extiende el backstop del bloque 3: ni huéspedes ni anfitriones suspendidos pueden crear/aprobar.
CREATE OR REPLACE FUNCTION public.enforce_motoposada_user_block()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_host_id UUID;
BEGIN
  IF NEW.status NOT IN ('pending','approved') THEN RETURN NEW; END IF;
  SELECT user_id INTO v_host_id FROM public.motoposadas WHERE id=NEW.motoposada_id;
  IF public.is_motoposada_suspended(NEW.guest_id) OR public.is_motoposada_suspended(v_host_id) THEN RAISE EXCEPTION 'motoposada_user_suspended'; END IF;
  IF EXISTS(SELECT 1 FROM public.motoposada_user_blocks b WHERE (b.blocker_id=NEW.guest_id AND b.blocked_id=v_host_id) OR (b.blocker_id=v_host_id AND b.blocked_id=NEW.guest_id)) THEN RAISE EXCEPTION 'motoposada_user_blocked'; END IF;
  RETURN NEW;
END $$;

REVOKE ALL ON FUNCTION public.get_motoposada_moderation_queue(TEXT), public.decide_motoposada_incident(BIGINT,TEXT,TEXT,TIMESTAMPTZ), public.appeal_motoposada_suspension(BIGINT,TEXT), public.review_motoposada_appeal(BIGINT,BOOLEAN,TEXT), public.is_motoposada_suspended(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_motoposada_moderation_queue(TEXT), public.decide_motoposada_incident(BIGINT,TEXT,TEXT,TIMESTAMPTZ), public.review_motoposada_appeal(BIGINT,BOOLEAN,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.appeal_motoposada_suspension(BIGINT,TEXT), public.is_motoposada_suspended(UUID) TO authenticated;
COMMIT;
