name: Build GraphHopper

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: graphhopper-router
  IMAGE_TAG: ghcr.io/eabarriostgc/graphhopper-router

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: graphhopper
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}:latest
            ${{ env.IMAGE_TAG }}:${{ github.sha }}
